name: Keep Streamlit App Awake
on:
  schedule:
    - cron: '0 */6 * * *' # Automatically pings every 6 hours
  workflow_dispatch:      # Allows manual trigger anytime

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://gigo-xero-zxeczpkv4wbafsntchzm72.streamlit.app/ > /dev/null
